theme: jekyll-theme-minimal
title: AnuraNet
description: AnuraNet is a collaborative expert network that promotes the development of vanguard techniques for acoustic monitoring of anurans and citizen-science. Our diverse community of researchers, technologists and conservationists that rise from Iberoamerican collaboration aims to foster and spread the tools key for enhancing our knowledge about anuran populations and their global trends.
